### ISSUE TITLE
运行GLUE数据库中的preprocess.py出现问题

### ISSUE THREAD

**Issue by SysuCodeRookie** [shizhediao/Black-Box-Prompt-Learning#5]
现在已经下载好了GLUE项目中的\glue_data里的所有原始数据文件，在其项目中提及，这些文件需要
After downloading GLUE, point in to the directory containing the data.PATH_PREFIXsrc/preprocess.py

但我在安装完所有需要的包之后，运行preprocess.py总是报错
Traceback (most recent call last):
  File "preprocess.py", line 13, in <module>
    from allennlp_mods.numeric_field import NumericField
  File "C:\Users\12408\Desktop\GLUE-baselines-master\GLUE-baselines-master\src\allennlp_mods\numeric_field.py", line 17, in <module>
    class NumericField(Field[numpy.ndarray]):
  File "C:\Users\12408\Desktop\GLUE-baselines-master\GLUE-baselines-master\src\allennlp_mods\numeric_field.py", line 74, in NumericField
    @overrides
  File "C:\Users\12408\anaconda3\envs\allennlp_env\lib\site-packages\overrides\overrides.py", line 83, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "C:\Users\12408\anaconda3\envs\allennlp_env\lib\site-packages\overrides\overrides.py", line 172, in _overrides
    _validate_method(method, super_class, check_signature)
  File "C:\Users\12408\anaconda3\envs\allennlp_env\lib\site-packages\overrides\overrides.py", line 191, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "C:\Users\12408\anaconda3\envs\allennlp_env\lib\site-packages\overrides\signature.py", line 103, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "C:\Users\12408\anaconda3\envs\allennlp_env\lib\site-packages\overrides\signature.py", line 304, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: NumericField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

现在的问题是，本实验所需的GLUE数据集是直接拿下载好的\glue_data中的.tsv文件，就可以运行pmi_ngram.py，还是说必须要经过preprocess.py？如果需要，请问上述报错如何处理？

**Comment by shizhediao** [comment]
您好，
您可以直接使用.tsv文件 以及处理好的candidate prompt vocabulary 跑实验。如果您已经下载了candidate prompt vocabulary，那么就不需要再运行'pmi_ngram.py'。
至于您提及的问题，我暂时不清楚原因，不过一个建议是使用linux系统环境。windows上可能会出现很多新的问题。谢谢！

------
Hi,

You can directly use the .tsv file along with the processed candidate prompt vocabulary to run experiments. If you have already downloaded the candidate prompt vocabulary, then there is no need to run 'pmi_ngram.py' again. As for the issue you mentioned, I am not sure of the reason at the moment, but one suggestion is to use a Linux system environment. There might be many new issues on Windows. Thank you

**Comment by SysuCodeRookie** [comment]
我已经下载好了candidate prompt vocabulary，放在项目文件夹的pmi文件夹中，为什么运行程序时还需要从外部下载数据集，导致自动重复运行多次的时候总是会因为网络波动而下载失败，导致重复运行停止？是需要在项目文件夹下另起一个dataset文件夹，把pmi文件夹中的txt文件搬过去，才能读取吗？能否设置优先从本地读取数据呢？
        
    if args.task_name is not None:
         # download the dataset.
        if args.task_name in task_to_keys.keys():
            raw_datasets = load_dataset("glue", args.task_name)
        else:
            raise(NotImplementedError)
    else:
        # Loading the dataset from local csv or json file.
        data_files = {}
        if args.train_file is not None:
            data_files["train"] = args.train_file
        if args.validation_file is not None:
            data_files["validation"] = args.validation_file
        if args.test_file is not None:
            data_files["test"] = args.test_file
        extension = (args.train_file if args.train_file is not None else args.valid_file).split(".")[-1]
        raw_datasets = load_dataset(extension, data_files=data_files)

**Comment by SysuCodeRookie** [comment]
请问文中提及有三个随机种子，除了42以外还有其他两个，请问是什么？

**Comment by shizhediao** [comment]
Hi,
另外两个应该是0和1.  做三次随机种子本身就是为了消除随机性带来的影响，理论上任意取三个随机种子也会有类似效果。
